### PR TITLE
Add style check workflow

### PR DESCRIPTION
**Pull request by warp-core**
Adds basic workflow to run the code style check @tibetiroka wrote for endless-sky.

### CODE REVIEW

**Comment by warp-core** [comment]
@Zitchas do you know what the action permissions are in this repository?

**Comment by tibetiroka** [comment]
I have a feeling you have to specify the source root in ci, because the layout is different than in the main repo. Not 100% sure though. I'll check when I'm home.

**Comment by Zitchas** [comment]
The settings for Actions are currently set to their most permissive level:
> Any action or reusable workflow can be used, regardless of who authored it or where it is defined. 

Likewise, workflows are likewise already set to the most permissive:
> Workflows have read and write permissions in the repository for all scopes.

(for comparison, these both match the settings for the main Endless Sky repository)

**Comment by warp-core** [comment]
Curious that it won't run them on the PR, then.
PRing the same branch to the master on my fork (currently synchronised with the master here) runs them.

**Pull request merged**
