### PR TITLE
Some improvements to file-check

### PR DESCRIPTION
**Pull request by warp-core**
Now includes the position of the bad character within the line. Starting with 1 for the first character in the line.

### CODE REVIEW

**Comment by warp-core** [comment]
@tehhowch @Zitchas could I get write access to this repository?

**Comment by Zitchas** [comment]
That seems reasonable. I have added you and @quyykk with write permissions.

**Comment by warp-core** [comment]
Thanks!

**Comment by warp-core** [comment]
@Zitchas can you also set the default to squash and merge?

**Comment by Zitchas** [comment]
Good idea. Done.

**Pull request merged**
